name: tests
run-name: Unit Tests - ${{ github.event.pull_request.title || github.event.head_commit.message || github.ref }}

on:
  workflow_call:
    inputs:
      elixir:
        required: true
        type: string
      otp:
        required: true
        type: string
      os:
        type: string
        default: ubuntu-latest

jobs:
  unit_test:
    name: Run Tests Elixir ${{ inputs.elixir }} OTP ${{ inputs.otp }} - ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.16.0
        with:
          otp-version: ${{ inputs.otp }}
          elixir-version: ${{ inputs.elixir }}

      - name: Restore dependencies cache
        id: mix_cache
        uses: actions/cache/restore@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ inputs.otp }}-${{ inputs.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ inputs.elixir }}-${{ inputs.otp }}-mix-

      - name: Run tests
        run: mix coveralls
